name: flutter_setup_task
description: Задание по Flutter - композиция виджетов и работа с API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon.png
  macos:
    generate: true
    image_path: assets/icon.png
